// This file is automatically generated from your CSS. Any edits will be overwritten.
export const home: string;
export const searchCombo: string;
export const search: string;
export const go: string;
