// This file is automatically generated from your CSS. Any edits will be overwritten.
export const instructions: string;
export const step: string;
export const recipeDescription: string;
export const itemTitle: string;
export const itemDetails: string;
export const itemSteps: string;
